---
  - name: Stopping httpd
    service:
      name: httpd
      state: stopped

  - name: Verify httpd state after stopping
    command: systemctl status crond
    #ignore_errors: yes
    changed_when: false
    register: result_status
    retries: 5
    until: result_status.rc == 3
    failed_when: result_status.rc == 0


#  - fail: msg="httpd is not stopped"
#    when: ( result_status.rc == 0 )
