---
  - block:
      - name: Stopping httpd
        service:
          name: httpd
          state: stopped

      - name: Verify httpd state after stopping
        command: systemctl status httpd
        register: result_status
        changed_when: false

      - fail: msg="httpd is not stopped"
        when: ("inactive" not in result_status.stdout)

    become: yes
    become_user: ansible
    tags: stopping


  - block:
      - name: Startng httpd
        service:
          name: httpd
          state: started

      - name: Make sure HTTP is running
        wait_for:
          host: 0.0.0.0
          port: 80
          delay: 3
          timeout: 300

    become: yes
    become_user: ansible
    tags: starting
