---
  - name: Check sudo privilege
    command: sudo -l -U "{{ ansible_user_id }}"
    args:
      warn: false
    register: result_sudo
    changed_when: false
    become: yes

  - fail: msg="Sudo privilege is missing!"
    when: ("ALL" not in result_sudo.stdout)
