---
  - name: Reboot OS
    shell: "sleep 5 && /usr/sbin/reboot"
    async: 1
    poll: 0

  - name: Wait for the reboot
    wait_for_connection:
      connect_timeout: 20
      sleep: 5
      delay: 5
      timeout: 300

  - name: "Check server uptime"
    shell: "uptime -p"
    register: uptime
