  - name: "Installing updates using yum"
  #  yum:
  #    name: "mc"
  #    state: absent
  #    #state: latest
  #    #update_only: "yes"
    command: /bin/sleep 30; echo "HELOOOOO VARDAN"
    async: 600
    poll: 5
    register: update_result
