- name: 'YUM - Update/Upgrade ALL repos'
  yum:
    name: '*'
    state: latest
    update_cache: yes
  async: 1000
  poll: 0
  register: update_sleeper

- name: 'YUM - Check for update status'
  async_status: jid={{ update_sleeper.ansible_job_id }}
  register: job_result
  until: job_result.finished
  retries: 100
