- hosts: all
  roles:
     - check-sudo-privilege
     - { role: stop-start-service, action: stop }
     - upgrade-os
     - { role: reboot, when: update_result is changed }
     - { role: stop-start-service, action: start }
  become: yes
